---
slack_settings: &slack_settings
  channel: '#govuk-smart-answers-devs'
  username: GOV.UK Ask Export
  icon_emoji: ':concourse:'
  silent: true
  always_notify: true

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: govuk-ask-export
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/govuk-ask-export
      branch: master
  - name: export-schedule
    type: time
    icon: timer 
    source:
      start: 1:01 AM
      stop: 1:05 AM
      location: Europe/London
  - name: gds-slack
    type: slack-notification
    icon: slack
    source:
      url: https://hooks.slack.com((slack-webhook-path))

jobs:
  - name: update-pipeline
    plan:
      - get: govuk-ask-export
        trigger: true
      - set_pipeline: govuk-ask-export
        file: govuk-ask-export/concourse.yml
 
  # - Export data from Smart Survey
  # - Split that into CSV files that are uploaded to Google Drive
  - name: scheduled-export
    serial: true
    plan:
      - get: export-schedule
        trigger: true
      - get: govuk-ask-export
      - task: file-export
        config:
          image_resource:
            type: registry-image
            source:
              repository: ruby
              tag: 2.6.6
          platform: linux
          inputs:
            - name: govuk-ask-export
          outputs:
            - name: export-output
              path: govuk-ask-export/output
          run:
            dir: govuk-ask-export
            path: /bin/bash
            args:
              - -c
              - |
                set -e
                bundle install --deployment
                bundle exec rake run_exports
          params:
            SINCE_TIME: 00:00
            UNTIL_TIME: 00:00
            SMART_SURVEY_API_TOKEN: ((smart-survey-api-token))
            SMART_SURVEY_API_TOKEN_SECRET: ((smart-survey-api-token-secret))
            SMART_SURVEY_CONFIG: live
            GOOGLE_ACCOUNT_TYPE: service_account
            GOOGLE_CLIENT_ID: ((google-client-id))
            GOOGLE_CLIENT_EMAIL: ((google-client-email))
            GOOGLE_PRIVATE_KEY: ((google-private-key))
            GOOGLE_CLOUD_PROJECT: ((google-cloud-project))
            FOLDER_ID_CABINET_OFFICE: ((google-drive-folder-id-cabinet-office))
            FOLDER_ID_THIRD_PARTY: ((google-drive-folder-id-third-party))
            AWS_REGION: eu-west-2
            AWS_ACCESS_KEY_ID: ((aws-access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
            S3_BUCKET_NAME_GCS_PUBLIC_QUESTIONS: ((aws-s3-bucket-name-gcs-public-questions))
        on_success:
          put: gds-slack
          params:
            <<: *slack_settings
            text: >
              :white_check_mark: <https://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Export successful>
        on_failure:
          put: gds-slack
          params:
            <<: *slack_settings
            text: >
              :x: <https://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Export failed> <!here>
        on_error:
          put: gds-slack
          params:
            <<: *slack_settings
            text: >
              :warning: <https://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Error occured with export> <!here>
