excluded_words:
  - 10 Downing Street
  - Absolute
  - Adviser
  - Afghanian
  - Alistair Campbell
  - All
  - Amber Rudd
  - Andrea Leadsom's
  - Andrew Marr
  - Anna Soubry
  - Applied
  - Arnold Schwarzenegger
  - Becouse
  - Being
  - Boris
  - Boris Johnson's
  - Boris Johnsons
  - borris johnson
  - Brexit
  - Brexiteers
  - Bricklayer
  - Brit
  - Britons
  - Brits
  - Bromley
  - Bus Driver
  - Bye
  - Cannot
  - Cant
  - Carer
  - Carers
  - Carpenter
  - Charity
  - Charity Trustee
  - Christ
  - Christian
  - Civil Servant
  - CMO
  - coronavirus
  - covid
  - covid-19
  - Coz
  - Cummings
  - Dad
  - Daughter
  - David Cameron
  - Dear Sir Madam
  - Death
  - Deceased
  - Democracy
  - Democrats
  - Disabled
  - Doctor
  - Dog
  - Dom Cummings
  - Dominic Cummings
  - Dominic Raab
  - DON'T
  - Dunno
  - Dutch
  - Electrician
  - England
  - Erasmus
  - European Commissioner
  - Europeans
  - Excellent
  - Eyvette Cooper
  - Family
  - Farmer
  - Freind
  - Friend
  - Friends
  - God
  - Gov
  - GOV UK
  - Gove
  - Happy
  - Have
  - Hello
  - HM Courts
  - Hope
  - Husband
  - Information Commissioner
  - ISA
  - Ive
  - Jacob Rees Mogg
  - Jacob Rees-Mogg
  - Jeremy Corbyn
  - Jesse Jackson
  - JESUS CHRIST
  - Jimmy Savile
  - Jobseekers
  - Johnson
  - Junior ISA
  - Just
  - Justin Trudeau
  - Kafka
  - Labourer
  - Landlord
  - Login
  - Love
  - Martin Lewis
  - Matt Hancock
  - Michael Gove
  - Michelle Obama
  - Mitt Romney
  - MPs
  - Mum
  - Mums
  - Muslims
  - Nan
  - Nancy Pelosi
  - National
  - Nigel Farage
  - NINO
  - No Deal Brexit
  - Nobody
  - Non
  - Nope
  - Nowhere
  - Nurse
  - October
  - Operation Yellowhammer
  - P.M
  - Parent
  - Passport
  - PIP
  - prince harry
  - Priti Patel
  - Priti Patel's
  - Probate
  - Quick
  - Rang
  - Read
  - Rees-Mogg
  - Refugees
  - Regards
  - Register
  - Research
  - Rt Hon
  - Self
  - Sir John Major
  - Social Worker
  - Solicitor
  - Solicitors
  - Son
  - SORN
  - step guide
  - Stop Brexit
  - Student
  - support@vehicleinformation.uk
  - Teach
  - Teresa Villiers
  - Terrible
  - Thatcher
  - Theresa May
  - Thomas Cook
  - Trustee
  - Trustees
  - Unemployed
  - Useless
  - Volunteer
  - Waiter
  - Want
  - Welsh
  - Why
  - Widows
  - Wife
  - Will
  - Wills
  - Yeah
  - Yellow Hammer
  - Yellowhammer
  - Zac Goldsmith
