---
pipelines:
  cabinet-office:
    destinations:
      - google_drive
    only_completed: true
    fields:
      - id
      - submission_time
      - region
      - name
      - email
      - phone
      - question_format
  third-party:
    destinations:
      - google_drive
    only_completed: true
    fields:
      - id
      - submission_time
      - region
      - question
      - question_format
  gcs-public-questions:
    destinations: []
    only_completed: true
    fields:
      - submission_time
      - region
      - question
