---
pipelines:
  cabinet-office:
    targets:
      - google_drive
    only_completed: true
    fields:
      - id
      - region
      - name
      - email
      - phone
      - share_video
  third-party:
    targets:
      - google_drive
    only_completed: true
    fields:
      - id
      - region
      - question
      - share_video
  gcs-public-questions:
    targets:
      - aws_s3
    only_completed: true
    fields:
      - submission_time
      - region
      - question
